### ISSUE TITLE
FLB, plotSegregation and pedigrees with loops

### ISSUE THREAD

**Issue by chrcarrizosa** [magnusdv/segregatr#3]
``` r
library(pedtools)
library(segregatr)
```

The BF cannot be computed in this example with loops, although the pedigree is still correctly displayed:

``` r
p0 = cousinPed(degree = 1) |>
  swapSex(ids = 8) |>
  addChildren(father = 7, mother = 8)
FLB(x = p0, freq = 0.001, penetrances = c(0,1,1),
    affected = c(3,7,9), unknown = 1,
    carriers = c(7,9), noncarriers = c(4,8),
    proband = 9, plot = TRUE)
#> Error in if (link == 0) return(sum(likel)): argument is of length zero
```

![](https://i.imgur.com/gYz1sZi.png)

After breaking the loops,`FLB()` returns NA, and markers are incorrectly positioned:

``` r
p1 = breakLoops(p0)
#> Loop breakers: 3
#> No further loops to break
FLB(x = p1, freq = 0.001, penetrances = c(0,1,1),
    affected = c(3,7,9), unknown = 1,
    carriers = c(7,9), noncarriers = c(4,8),
    proband = 9, plot = TRUE)
```

![](https://i.imgur.com/7jVAIeF.png)

    #> [1] NaN

By specifying the new individual ‘=3’ a numeric result is obtained, but the problem with the markers remains:

``` r
FLB(x = p1, freq = 0.001, penetrances = c(0,1,1),
    affected = c(3,7,9,'=3'), unknown = 1,
    carriers = c(7,9), noncarriers = c(4,8),
    proband = 9, plot = TRUE)
```

![](https://i.imgur.com/m90jv42.png)

    #> [1] 5.01503

The value of the BF is at least different from a pedigree where 3 and =3 are different individuals:

``` r
p2 = nuclearPed(nch = 2, sex = 1) |>
  addChildren(fa = 4, sex = 2) |>
  addChildren(mo = 6, sex = 1) |>
  addParents(id = 7)
#> Mother: Creating new individual with ID = 5
#> Father: Creating new individual with ID = 7
#> Father: Creating new individual with ID = 9
#> Mother: Creating new individual with ID = 10
FLB(x = p2, freq = 0.001, penetrances = c(0,1,1),
    affected = c(3,7,8,9), unknown = 1,
    carriers = c(7,8), noncarriers = c(6,10),
    proband = 8, plot = TRUE)
```

![](https://i.imgur.com/UJc8KkD.png)

    #> [1] 4.012024

Also note that the markers are again incorrectly plotted, even though there were no loops in this case.

<sup>Created on 2021-12-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by magnusdv** [comment]
Thanks for bringing this up. The simple explanation is that `FLB()` did not support looped pedigrees at all, and also didn't know that it didn't... 

In f88ec20 I have added rudimentary support for loops, so that your example at least runs cleanly:
``` r
library(segregatr)
#> Loading required package: pedtools

p0 = cousinPed(degree = 1, child = T)

FLB(p0, freq = 0.001, penetrances = c(0,1,1),
    affected = c(3,7,9), unknown = 1,
    carriers = c(7,9), noncarriers = c(4,8),
    proband = 9)
#> [1] 5.01503
```

<sup>Created on 2021-12-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

However, there are some wrinkles remaining, and I have not checked if the answer above is correct.

Do you know any looped examples where the answer can be verified by hand calculation or other means?

**Comment by chrcarrizosa** [comment]
Great, thanks! The results seem correct. I have added some calculations for this example and others with loops in the tests.
